import Authprovider from '@/context/AuthProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Authprovider>
        <body >
          {children}
        </body>
      </Authprovider>
    </html>
  )
}
